'use strict';
const $=id=>document.getElementById(id);let timer=null,busy=false;
function badge(status){const span=document.createElement('span');span.className='badge '+status;span.textContent=status;return span;}
function suiteCard(suite,running){const card=document.createElement('article');card.className='suite';const h=document.createElement('h2');h.textContent=suite.label;const p=document.createElement('p');p.textContent=suite.description;const steps=document.createElement('ol');for(const label of suite.steps){const li=document.createElement('li');li.textContent=label;steps.append(li)}const button=document.createElement('button');button.textContent=suite.id==='release'?'Run full validation':'Run '+suite.label;button.disabled=running||busy;button.onclick=()=>run(suite.id);card.append(h,p,steps,button);return card;}
function runCard(run){const box=document.createElement('article');box.className='run';const head=document.createElement('div');head.className='run-head';const title=document.createElement('strong');title.textContent=run.label;head.append(title,badge(run.status));const detail=document.createElement('p');detail.textContent=run.status==='running'?`Step ${run.step_index} of ${run.step_count}: ${run.step}`:`Finished ${run.finished_at||''}`;box.append(head,detail);if(run.status==='running'){const progress=document.createElement('div');progress.className='progress';const fill=document.createElement('div');fill.style.width=Math.max(4,Math.round((run.step_index-1)/run.step_count*100))+'%';progress.append(fill);box.append(progress)}if(run.steps?.length){const list=document.createElement('ol');for(const step of run.steps){const item=document.createElement('li');item.textContent=`${step.label}: ${step.status}${step.exit_code==null?'':` (exit ${step.exit_code})`}`;list.append(item)}box.append(list)}return box;}
function render(data){const current=data.current,running=current?.status==='running';$('state').textContent=running?'Running':'Idle';$('latest').textContent=data.history[0]?.status||'—';$('count').textContent=data.history.length;$('suites').replaceChildren(...data.suites.map(s=>suiteCard(s,running)));if(current){$('active').className='';$('active').replaceChildren(runCard(current));$('console').hidden=!current.log?.length;$('console').textContent=(current.log||[]).join('\n');$('console').scrollTop=$('console').scrollHeight}else{$('active').className='empty';$('active').textContent='No test is running.';$('console').hidden=true}$('history').className=data.history.length?'':'empty';$('history').replaceChildren(...(data.history.length?data.history.map(runCard):[document.createTextNode('No saved test results yet.')]));schedule(running?750:5000)}
async function load(){try{const response=await fetch('/api/tests',{cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error||'Could not load test results.');render(data)}catch(error){$('state').textContent='Unavailable';$('active').className='empty';$('active').textContent=error.message;schedule(5000)}}
async function run(suite){if(busy)return;busy=true;if(timer)clearTimeout(timer);try{const response=await fetch('/api/tests/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({suite})}),data=await response.json();if(!response.ok)throw new Error(data.error||'Could not start tests.');await load()}catch(error){$('active').className='empty';$('active').textContent=error.message;schedule(3000)}finally{busy=false}}
function schedule(delay){if(timer)clearTimeout(timer);timer=setTimeout(load,delay)}load();
